### PR TITLE
Abaqus mixed interface

### LINKED ISSUE #78: Abaqus wrapper: allow mixed interface
Currently, the Abaqus wrapper cannot handle an interface which has mixed element types (e.g. when using a hexdominant mesh). 

The error starts with the [make_elements function](https://github.com/pyfsi/coconut/blob/78281e4d8e7f4a929058cb70e0e1b88e1ed1d435/coupling_components/solver_wrappers/abaqus/614.py#L554) writing the number of load points of _the last face it has looped over_. This value is read again [later on in the code](https://github.com/pyfsi/coconut/blob/78281e4d8e7f4a929058cb70e0e1b88e1ed1d435/coupling_components/solver_wrappers/abaqus/614.py#L247) as `n_lp`. Eventually something goes wrong [when the input modelpart is created](https://github.com/pyfsi/coconut/blob/78281e4d8e7f4a929058cb70e0e1b88e1ed1d435/coupling_components/solver_wrappers/abaqus/614.py#L263-L278). In the example of mixed triangular and quadrilateral faces, `n_lp` is either 3 or 4. For looping over the faces file the product `n_elem*n_lp` is used as range. But if `n_lp`was put on 3, too little lines of the faces file will be read (as some elements have 4 lines). It is not clear where it would go wrong, maybe a bounding box error would be raised about the interfaces, but it's also possible that the interpolation will just be inadequate. If `n_lp` was put on 4, then the reading of the faces file will be continued too far, raising [this error](https://github.com/pyfsi/coconut/blob/78281e4d8e7f4a929058cb70e0e1b88e1ed1d435/coupling_components/solver_wrappers/abaqus/614.py#L272).

I think this can be solved by changing the way we loop over the faces file.

### PR DESCRIPTION
**Pull request by awbral**
**Description** Briefly describe what has been changed or improved.  

For Abaqus, it is now possible to have different element types (i.e. number of load points differs between elements) in the same interface.

**Users' experience affected?** It is useful to mention whether the change affects the users' experience (e.g. when the JSON-file needs to be adapted).

N/A

**Other parts of the code affected?** If other parts of the code are affected, please notify the responsible of that part using [@mentions](https://docs.github.com/en/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams).

N/A

**Tests** Have you tested the code? What did you verify?

- unit tests pass locally (no changes)
- `test_single_solver` with varying pressure load (sinusoidal in time, linear in space) on 3D tube with mixed interface and the original quadrilateral interface from the Abaqus 3D example was compared with master for both 1 and 5 cores. Results match.
- `tube_tube_flow_abaqus2d` was compared between master and branch. Results and convergence history are identical.
- `tube_fluent3d_abaqus3d` was compared between master and branch for both the original setup (quadrilateral interface) and mixed interface. Results and convergence history for the quad interface are identical between master and branch. The mixed interface case still crashes after 33 time steps due to Abaqus divergence. However, displacements match the quad interface cases before the crash. I will provide a new mesh later on.

**Related issues** If the pull request closes issues, [link it](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).

Closes #78

**Checklist**
- [x] Style guidelines
    1. CoCoNuT follows [the PEP8 style guide](https://www.python.org/dev/peps/pep-0008/).
    2. Comments should be lowercase.
    3. Errors should start with capitals, preferably without punctuation unless it's multiple sentences.
    4. Strings should use single quotes whenever possible.	
- [x] Self-review of code performed
- [x] Code has been commented (particularly in hard-to-understand areas)
- [x] Documentation was updated correspondingly
- [x] New and existing unit tests pass locally with changes

### CODE REVIEW

**Comment by hdolfen** [comment]
Did you also do the tube_tube_flow_abaqus2d test with the mixed interface mesh? Did the results match (more or less) there?

**Comment by awbral** [comment]
No, I only made a mesh for the Abaqus 3D case. Would it be useful to adapt the example with an appropriate mapper to go from tube_flow to abaqus3D?

**Comment by hdolfen** [comment]
> No, I only made a mesh for the Abaqus 3D case. Would it be useful to adapt the example with an appropriate mapper to go from tube_flow to abaqus3D?

I'm sorry I didn't think of the fact that it's 2D, I don't think there's a true mixed interface there unless maybe by mixing linear and quadratic elements? Maybe that's also an approach to test the 3D case again, with 1st order and 2nd order quad cells.

**Comment by awbral** [comment]
Good point, was thinking of that as well for an instant.

**Review by hdolfen — APPROVED** [review]

**Pull request merged**
