### PR TITLE
Turek benchmark

### LINKED ISSUE #41: Additional example cases
Currently the example cases are limited to variations of the tube (1D, 2D, 3D, mixed...). 
I think it would be useful to have a few more example cases (although not necessarily as many as Tango has), so that the user has some more variation as inspiration. E.g. an example where the Interface consists of several ModelParts would be nice. 
Also, I don't think an example should work with each version of the software (e.g. different Fluent versions), because that would be too hard to maintain, and would lead to too much code.

### LINKED ISSUE #58: Abaqus: use case setup scripts in examples
I noticed that for the Fluent-side of the test examples, the mesh file and case file is created using journals. Currently we start from a complete inp-file in Abaqus. As we refer a lot to the Python interface of Abaqus in the documentation, it's maybe nice to have some examples using a Python script to generate the .inp file, either starting from scratch or starting from an existing mesh file. (I have some code to create a continuum elements mesh file for a clamped-clamped tube in case we would choose that.)

### PR DESCRIPTION
**Pull request by nicolasdlss**
**Description** Restructure Abaqus examples (rename .inp file and how setup works)(also in tests) and add Turek example
Import of make_surface in make_inp is adjusted. (deletion of make_host_file.sh is done in other PR)

**Users' experience affected?** Abaqus example now start from mesh and build input file using Python interface of Abaqus

**Other parts of the code affected?** NA

**Tests** Default tests run as well as Abaqus tests. All examples have been run for two time steps.

**Related issues** Closes #41 Closes #58 

An image to of the Turek FSI2 case still has to be added in the documentation.

**Checklist**
- [x] Style guidelines
    1. CoCoNuT follows [the PEP8 style guide](https://www.python.org/dev/peps/pep-0008/).
    2. Comments should be lowercase.
    3. Errors should start with capitals, preferably without punctuation unless it's multiple sentences.
    4. Strings should use single quotes whenever possible.	
- [x] Self-review of code performed
- [x] Code has been commented (particularly in hard-to-understand areas)
- [x] Documentation was updated correspondingly
- [x] New and existing unit tests pass locally with changes

### CODE REVIEW

**Comment by hdolfen** [comment]
I made some small changes to avoid all the duplicate files.
In the setup files I sourced the *`make_hostfile.sh`* via a relative path.
In the `make_inp.py` files I added the extra folder to the Python path such that *`make_surface.py`* can be imported directly.

@nicolasdlss and @awbral do you agree with this way of doing it? Alternatively we could copy these files to the CSM folder using a relative path.

**Comment by awbral** [comment]
Is it an option to source the make_hostfile.sh directly in the `__ init __` method of the Abaqus wrapper? Or is this not done as the script is system specific?

**Review by hdolfen — APPROVED** [review]

**Comment by hdolfen** [comment]
@awbral I was planning to look into that. I haven't done it so far because I'm not sure how system specific it is.

**Comment by hdolfen** [comment]
@awbral I was planning to look into that. I haven't done it so far because I'm not sure how system specific it is.

**Comment by nicolasdlss** [comment]
Hm, I am honestly not a big fan of these relative paths. They can break quite easily.
When I am testing the examples,  for example, I copy them to a _`tmp`_ folder, which will immediately break these paths.

For the _`make_surface.inp`_, I propose to import them from coconut, as that path should be in the Python path anyway: 
`from coconut.coupling_components.solver_wrappers.abaqus.extra.makeSurface import *`

For _`make_host_file.sh`_, in my opinion, the whole setup is overly complicated:
```
rm -f AbaqusHosts.txt
NPROC=$(nproc --all)  # count the number of processors
NAME=$(hostname | sed -e 's/.ugent.be//')  # remove ".ugent.be" from the hostname

for i in $(seq 1 $NPROC)
do
echo $NAME >> AbaqusHosts.txt  # print the hostname to the file as many times as there are processors
done
```
The file is then used in quite elaborate bit of code to put the following line in the environment file: 
`mp_host_list=[['<host_name1>', <num_of_cores1>], [<host_name2>, <num_of_cores2>]]`
On the other hand, the environment file has the system specific license server as well, so it is already no longer general...
Clearly, the approach needs to be optimized, For the time being however, I would leave the _`make_host_file.sh`_ as is, to avoid problems with the relative path.

**Comment by hdolfen** [comment]
As to using an absolute import in * `make_inp.py`*, I already tried that. It does not work because Abaqus works with Python 2 and coconut is a Python 3 package. The *`make_surface.py`* script is Python 2 code. It's not possible to import it like that without running the *`__init__.py`* file and that causes an error.

The creation of the hostfile can indeed be optimized and is maybe even unneeded. I think it is not needed as long as you don't run Abaqus with MPI (which is not needed for single-machine use).

As to the use of relative paths, I don't really have a good solution for this. Leaving many copies of a file is in my opinion also not good, because it's easy to miss one when updating them.

**Comment by awbral** [comment]
As these two files are Abaqus-specific and are identical for different cases, isn't it an option to put those in a single "*`abaqus_general`* folder in the *`setup_files`* folder? As such, there is only one version

**Comment by hdolfen** [comment]
That's indeed an option, but what is the difference with the extra folder?

**Comment by nicolasdlss** [comment]
The idea from Axel is indeed an option, as the then the files can be located with respect to the _`setup_files`_ folder. That's fine and will always be needed.

To keep in it in the _`extra`_ folder, the following import in the _`make_inp.py`_ file works:
```
import imp
import sys
coconut_path = imp.find_module('coconut')[1]
sys.path.append(coconut_path + '/coupling_components/solver_wrappers/abaqus/extra')
from make_surface import *
```

**Comment by hdolfen** [comment]
Okay as I understand you copy the entire *`examples`* directory to a *`tmp`* folder? Then indeed relative to *`setup_files`* is different than relative to the *`extra`* folder.

For me both options are good. If we choose to put it under the *`examples`* folder, do we keep the *`extra`* folder then?

**Comment by nicolasdlss** [comment]
I prefer to keep it in the _`extra`_ folder as it avoids the additional copy command and operation and keeps it more clean, but if you prefer the other way, that's also fine for me.

**Pull request merged**
