### PR TITLE
Feature fluent new versions

### PR DESCRIPTION
**Pull request by toondm**
I added new solver-wrappers for 3 Fluent versions: 2019R2, 2019R3 and 2020R1. 

Nothing really changed, so the journal and UDF files are mostly copied, and for the main Python class inheritance is used. 
The same is done for the test cases. 

In 2019R3 (and 2020R1) the behavior of Fluent after restart has changed, which is super weird. However, it still gives almost exactly the same result after 100 iterations of the test-example with 3D Fluent and 3D Abaquas, so I guess it's not important.

### CODE REVIEW

**Comment by hdolfen** [comment]
Thanks for your work Toon!

About the weird restart behavior, should we open an issue in order not to forget that this behavior is there? Otherwise some future user maybe won't get why his unit tests don't work.

Only action I can think of however is contacting the Fluent helpdesk, I'm really clueless about what can cause this.

**Comment by joris13** [comment]
Indeed, thanks for updating this wrapper! And also good suggestion to contact the Fluent support. Please start that process, as it can take a while...

**Comment by toondm** [comment]
@hdolfen I adapted the unit test for 2019R3 and 2020R1, by setting the tolerance for that one test much lower, so it does not crash. I've also mentioned the issue in the documentation. 
@joris13 I'll try to contact Fluent support.

**Comment by toondm** [comment]
So... I think I found the problem. I was trying to make a minimal working example to report to the customer service, and long story short, I discovered that the problem disappeared when doing either: 

- turning off mesh smoothing
- running on a single core

This makes me think that the strange behavior on restart is due to the following adaption in 2019R3:
*For parallel cases with smoothing that do not use dynamic load balancing, a zonal partitioning with Laplace smoothing will automatically be applied when the file is read, which should result in better load balancing for the mesh smoothing calculations.*
Because the domain has already deformed, the restart reads in a different domain, uses different partitioning (for the smoothing only!) and therefore results in a different mesh deformation and hence a slightly different result. Sounds legit?

Anyway, I now run the unit test that tests restart capabilities on a single core and with the old tolerance (1e-14), and now all tests with 2019R3 and 2020R1 are successful (and a bit slower). 
I've also put a note about those Fluent changes in the documentation.

**Comment by joris13** [comment]
That explanation is in line with the tiny differences that are observed. Good solution. Maybe run the unit test on single core with the  strict tolerance and then also on multiple cores with a bit less stringent tolerance. Can you see it in the residuals only or also significantly in the resulting pressure?

**Comment by toondm** [comment]
> Can you see it in the residuals only or also significantly in the resulting pressure?

On multiple cores, the relative difference in pressure was a bit over 1e-4 (for the 3D tube), so then I had to set the criterion to 1e-3 to avoid failing the unit test, which is too high for a good-quality unit test in my opinion. Running that specific unit test on a single core gives exactly the same residuals and hence pressure. The large pressure difference on multiple cores is probably due to the large mesh deformations that are used in the unit tests, which means the mesh smoothing can be quite different with and without restart.
Also, there is another unit test that specifically checks performance on multiple cores (comparing 1 CPU and max # CPUs), so that is covered already in the unit tests.

**Review by nicolasdlss — APPROVED** [review]

**Comment by joris13** [comment]
Can the unit test be repeated for a small deformation? Then also in parallel a restart should not have so much effect. Otherwise this has to be reported to Ansys (which sucks, I know). Almost all calculations are in parallel and restarts happen so frequently, so a parallel restart should not influence the results in a significant way...

**Comment by toondm** [comment]
@joris13 : if I repeat the unit-test with smaller deformations, the relative pressure difference decreases proportionally. 
This particular restart behavior is new in v2019R3, but similar differences can be found in older versions, e.g. by deforming the mesh on a different number of cores and comparing the solutions. @hdolfen recently had some issues with that in v18.2, and 2019R3 actually provided more stable mesh smoothing, so the changes by the Fluent team seem like an improvement.

**Pull request merged**
